repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict

- repo: https://github.com/nvuillam/npm-groovy-lint
  rev: v14.6.0
  hooks:
  -   id: npm-groovy-lint
      args: [--format]
      files: '(Jenkinsfile|.*\.jenkins)$'
  -   id: npm-groovy-lint
      args: [--fix, --failon=warning]
      files: '(Jenkinsfile|.*\.jenkins)$'

-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
    -   id: terraform_fmt
        args:
        - --args=-recursive
    -   id: terraform_validate
